<?php
$frases = array(
'Cada día sabemos más y entendemos menos <em>Albert Einstein<em>',
'No hay nada que un hombre no sea capaz de hacer cuando una mujer le mira <em>Casanova<em>',
'Ningún hombre es lo bastante bueno para gobernar a otros sin su consentimiento <em>Abraham Lincoln<em>',
'Vivir sola es como estar en una fiesta donde nadie te hace caso <em>Marilyn Monroe<em>',
'El mundo es bello, pero tiene un defecto llamado hombre <em>Friedrich Nietzsche<em>',
'Pienso, luego existo <em>René Descartes<em>',
'Sólo puede ser feliz siempre el que sepa ser feliz con todo <em>Confucio<em>',
'Ser o no ser, ésa es la cuestión <em>Shakespeare<em>',
'No pain no gain <em>Benjamín Franklin<em>',
'Solo sé que no sé nada <em>Sócrates<em>',
'La mejor manera de librarse de la tentación es caer en ella <em>Oscar Wilde<em>',
'Uno es dueño de lo que calla y esclavo de lo que habla <em>Sigmund Freud<em>',
'El que va demasiado aprisa llega tan tarde como el que va muy despacio <em>Shakespeare<em>',
'La vida es maravillosa si no se le tiene miedo <em>Charles Chaplin<em>',
'Sé tú, e intenta ser feliz, pero sobre todo, sé tú <em>Charles Chaplin<em>',
'A la muerte se le toma de frente con valor y después se le invita a una copa <em>Edgar Allan Poe<em>',
'Más cuerdo es, el que acepta su propia locura <em>Edgar Allan Poe<em>',
'Dos cosas son infinitas: el Universo y la estupidez humana; y yo no estoy seguro sobre el Universo <em>Albert Einsten<em>',
'Si lo puedes soñar, lo puedes hacer <em>Walt Disney<em>',
'La vida es lo que te pasa mientras estás ocupado haciendo otros planes <em>John Lennon<em>',
'El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora <em>Proverbio Chino<em>',
'Nunca pienso en las consecuencias de fallar un gran tiro… cuando se piensa en las consecuencias se está pensando en un resultado negativo - Michael Jordan',
'El dinero no es la clave del éxito; la libertad para poder crear lo es - Nelson Mandela',
'Cuanto más duramente trabajo, más suerte tengo - Gary Player',
'La inteligencia consiste no sólo en el conocimiento, sino también en la destreza de aplicar los conocimientos en la práctica - Aristóteles',
'El trabajo duro hace que desaparezcan las arrugas de la mente y el espíritu - Helena Rubinstein', 
'Cuando algo es lo suficientemente importante, lo haces incluso si las probabilidades de que salga bien no te acompañan - Elon Musk',
'Escoge un trabajo que te guste, y nunca tendrás que trabajar ni un solo día de tu vida - Confucio',
'Un sueño no se hace realidad por arte de magia, necesita sudor, determinación y trabajo duro - Colin Powell',
'Cuéntamelo y me olvidaré. enséñamelo y lo recordaré. involúcrame y lo aprenderé - Benjamin Franklin', 
'La lógica te llevará de la a a la z. la imaginación te llevará a cualquier lugar - Albert Einstein',
'A veces la adversidad es lo que necesitas encarar para ser exitoso - Zig Ziglar ',
'Para tener éxito tu deseo de alcanzarlo debe ser mayor que tu miedo al fracaso - Bill Cosby',
'Ejecuta tus conocimientos con la maestría del que sigue aprendiendo - Jonathan García-Allen',
'Cuando pierdas, no pierdas la lección - Dalai Lama ',
'No busques los errores, busca un remedio - Henry Ford',
'La vida es una aventura, atrévete - Teresa de Calcuta',
'Tu actitud, no tu aptitud, determinará tu altitud - Zig Ziglar',
'Tienes que hacer las cosas que crees que no puedes hacer - Eleanor Roosevelt',
'Si te caíste ayer, levántate hoy - H. G. Wells',
'Siempre parece imposible... hasta que se hace - Nelson Mandela',
'Si no pierdes, no puedes disfrutar de las victorias - Rafael Nadal',
'No dejes que el miedo se interponga en tu camino - Babe Ruth',
'Haz de cada día tu obra maestra John Wooden ',
'No cuentes los días, haz que los días cuenten - Muhammad Ali',
'El mejor momento del día es ahora - Pierre Bonnard',
'Si la oportunidad no llama, construye una puerta - Milton Berle',
'Deja que cada hombre ejerza el arte que domina - Aristófanes ',
'El valor de una idea radica en su uso - Thomas Edison',
'Puedo aceptar el fracaso pero no puedo aceptar no intentarlo - Michael Jordan',
'La mejor forma de predecir el futuro es creándolo - Abraham Lincoln ',
'Un día despertarás y descubrirás que no tienes más tiempo para hacer lo que soñabas. El momento es ahora. Actúa - Paulo Coelho',
'Hoy eres un lector y mañana serás un líder - Margaret Fuller',
'Los dos guerreros más poderosos son la paciencia y el tiempo - León Tolstói',
'No puedes derrotar a la persona que nunca se rinde - Babe Ruth',
'El secreto de tu éxito está determinado por tu agenda diaria - John C. Maxwell',
'Recordar que vas a morir, es la mejor manera que conozco para no pensar que tienes algo que perder. Ya estás desnudo. No hay ninguna razón para no seguir a tu corazón - Steve Jobs',
'Se lo suficientemente valiente para vivir de forma creativa. El lugar creativo donde nadie ha estado - Alan Alda',
'Cuando dejo ir lo que soy, me convierto en lo que debería ser - Lao Tzu',
'Apunta a la luna. Si fallas, podrías dar a una estrella - William Clement Stone ',
'Existe al menos un rincón del universo que con toda seguridad puedes mejorar, y eres tú mismo - Aldous Huxley',
'El verdadero buscador crece y aprende, y descubre que siempre es el principal responsable de lo que sucede - Jorge Bucay',
'Escribir es un oficio que se aprende escribiendo - Simone de Beauvoir',
'La forma más rápida de cambiar es convivir con personas que ya son como quieres ser - Reid Hoffman'
);

    

    
    $jsonfrases = json_encode($frases);
    $archivo = fopen('frases.json','a');
    fputs($archivo,$jsonfrases);
    fclose($archivo);  
    
